import os

OPENAI_API_KEY= os.environ['OPENAI_API_KEY']
SERPAPI_API_KEY= os.environ['SERPAPI_API_KEY']
PERPLEXITY_API_KEY= os.environ['PERPLEXITY_API_KEY']
FLASK_SECRET_KEY= os.environ['FLASK_SECRET_KEY']